<?php 
return array (
  'timestamp' => 1749764587,
  'site_id' => 1,
  'group' => 'transient',
  'key' => 'ecwid_products_ca29c9d7de905172bf57ec92719ae527',
  'type' => 'array',
  'timeout' => 1750369387,
  'data' => 
  array (
    'time' => 1749764587,
    'data' => 
    (object) array(
       'id' => 758879708,
       'sku' => '0009',
       'thumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051691238.jpg',
       'unlimited' => true,
       'inStock' => true,
       'name' => 'SAMPLE. Sleeveless Jeans Jacket',
       'nameTranslated' => 
      (object) array(
         'en' => 'SAMPLE. Sleeveless Jeans Jacket',
      ),
       'price' => 159.95,
       'priceInProductList' => 159.95,
       'defaultDisplayedPrice' => 159.95,
       'defaultDisplayedPriceFormatted' => '$159.95',
       'costPrice' => 0,
       'tax' => 
      (object) array(
         'taxable' => true,
         'defaultLocationIncludedTaxRate' => 0,
         'enabledManualTaxes' => 
        array (
        ),
         'taxClassCode' => 'default',
      ),
       'lowestPriceSettings' => 
      (object) array(
         'lowestPriceEnabled' => false,
      ),
       'isShippingRequired' => true,
       'hasFreeShipping' => true,
       'weight' => 0,
       'url' => 'https://dcandles.ctrlaltcarter.com/store/sample-sleeveless-jeans-jacket',
       'autogeneratedSlug' => 'sample-sleeveless-jeans-jacket',
       'customSlug' => '',
       'created' => '2025-06-12 00:16:12 +0000',
       'updated' => '2025-06-12 00:16:12 +0000',
       'createTimestamp' => 1749687372,
       'updateTimestamp' => 1749687372,
       'productClassId' => 0,
       'enabled' => true,
       'options' => 
      array (
        0 => 
        (object) array(
           'type' => 'SIZE',
           'name' => 'Size',
           'nameTranslated' => 
          (object) array(
             'en' => 'Size',
          ),
           'choices' => 
          array (
            0 => 
            (object) array(
               'text' => 'S',
               'textTranslated' => 
              (object) array(
                 'en' => 'S',
              ),
               'priceModifier' => 0,
               'priceModifierType' => 'ABSOLUTE',
            ),
            1 => 
            (object) array(
               'text' => 'M',
               'textTranslated' => 
              (object) array(
                 'en' => 'M',
              ),
               'priceModifier' => 0,
               'priceModifierType' => 'ABSOLUTE',
            ),
            2 => 
            (object) array(
               'text' => 'L',
               'textTranslated' => 
              (object) array(
                 'en' => 'L',
              ),
               'priceModifier' => 0,
               'priceModifierType' => 'ABSOLUTE',
            ),
          ),
           'defaultChoice' => 0,
           'required' => false,
        ),
      ),
       'warningLimit' => 0,
       'fixedShippingRateOnly' => false,
       'fixedShippingRate' => 0,
       'shipping' => 
      (object) array(
         'type' => 'GLOBAL_METHODS',
         'methodMarkup' => 0,
         'flatRate' => 0,
         'disabledMethods' => 
        array (
        ),
         'enabledMethods' => 
        array (
        ),
      ),
       'defaultCombinationId' => 0,
       'imageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051691236.jpg',
       'smallThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051691235.jpg',
       'hdThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051691237.jpg',
       'originalImageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051691234.jpg',
       'originalImage' => 
      (object) array(
         'url' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051691234.jpg',
         'width' => 1280,
         'height' => 1919,
      ),
       'borderInfo' => 
      (object) array(
         'dominatingColor' => 
        (object) array(
           'red' => 228,
           'green' => 227,
           'blue' => 225,
           'alpha' => 255,
        ),
         'homogeneity' => true,
      ),
       'description' => '<p>This vintage jeans jacket is our bestseller. It has a spread collar, four pockets,
				button closure, sleeveless and straight hem. Will do for a movie night with friends, city walk, skating
				on an empty parking lot, and other casual occasions in all seasons. This jacket is lightweight, durable
				and soft.</p><p>Perfectly paired with our red and white horizontal striped T-shirt or bright
				yellow track pants. Will look great with almost every t-shirt or jeans. </p><div>Available
				in S, M, and L sizes.</div><p><strong>Fabric & care</strong></p><p><strong>Material</strong>:
				80% Cotton, 10% Polyester, 10% Spandex<br><strong>Color</strong>: Blue<br><strong>Fit</strong>:
				Relaxed<br><strong>Sleeve type</strong>: Sleeveless<br>We recommend hand-washing
				your jacket: use a basic and mild detergent, soak your jacket in cold water and let it be for at least
				an hour. After the soaking, rub any specially stained areas gently by rubbing with your hands and then
				rinse the jacket with more cold water before letting the jacket dry on its own.</p>
			',
       'descriptionTranslated' => 
      (object) array(
         'en' => '<p>This vintage jeans jacket is our bestseller. It has a spread collar, four pockets,
				button closure, sleeveless and straight hem. Will do for a movie night with friends, city walk, skating
				on an empty parking lot, and other casual occasions in all seasons. This jacket is lightweight, durable
				and soft.</p><p>Perfectly paired with our red and white horizontal striped T-shirt or bright
				yellow track pants. Will look great with almost every t-shirt or jeans. </p><div>Available
				in S, M, and L sizes.</div><p><strong>Fabric & care</strong></p><p><strong>Material</strong>:
				80% Cotton, 10% Polyester, 10% Spandex<br><strong>Color</strong>: Blue<br><strong>Fit</strong>:
				Relaxed<br><strong>Sleeve type</strong>: Sleeveless<br>We recommend hand-washing
				your jacket: use a basic and mild detergent, soak your jacket in cold water and let it be for at least
				an hour. After the soaking, rub any specially stained areas gently by rubbing with your hands and then
				rinse the jacket with more cold water before letting the jacket dry on its own.</p>
			',
      ),
       'galleryImages' => 
      array (
        0 => 
        (object) array(
           'id' => 1,
           'url' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051755608.jpg',
           'thumbnail' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051755609.jpg',
           'originalImageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051755608.jpg',
           'imageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051755610.jpg',
           'hdThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051755611.jpg',
           'thumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051755612.jpg',
           'smallThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051755609.jpg',
           'width' => 1280,
           'height' => 1920,
           'orderBy' => 0,
           'borderInfo' => 
          (object) array(
             'dominatingColor' => 
            (object) array(
               'red' => 233,
               'green' => 233,
               'blue' => 232,
               'alpha' => 255,
            ),
             'homogeneity' => false,
          ),
        ),
      ),
       'media' => 
      (object) array(
         'images' => 
        array (
          0 => 
          (object) array(
             'id' => '0',
             'isMain' => true,
             'orderBy' => 0,
             'image160pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051691235.jpg',
             'image400pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051691238.jpg',
             'image800pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051691237.jpg',
             'image1500pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051691236.jpg',
             'imageOriginalUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051691234.jpg',
          ),
          1 => 
          (object) array(
             'id' => '1',
             'isMain' => false,
             'orderBy' => 1,
             'image160pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051755609.jpg',
             'image400pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051755612.jpg',
             'image800pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051755611.jpg',
             'image1500pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051755610.jpg',
             'imageOriginalUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051755608.jpg',
          ),
        ),
         'videos' => 
        array (
        ),
      ),
       'categoryIds' => 
      array (
      ),
       'categories' => 
      array (
      ),
       'defaultCategoryId' => 0,
       'attributes' => 
      array (
      ),
       'files' => 
      array (
      ),
       'relatedProducts' => 
      (object) array(
         'productIds' => 
        array (
        ),
         'relatedCategory' => 
        (object) array(
           'enabled' => false,
           'categoryId' => 0,
           'productCount' => 1,
        ),
      ),
       'combinations' => 
      array (
      ),
       'volume' => 0,
       'showOnFrontpage' => 7,
       'isSampleProduct' => true,
       'googleItemCondition' => 'NEW',
       'isGiftCard' => false,
       'discountsAllowed' => true,
       'productCondition' => 'NEW',
       'outOfStockVisibilityBehaviour' => 'SHOW',
       'seo_link' => 'https://dcandles.ctrlaltcarter.com/store/sample-sleeveless-jeans-jacket',
    ),
  ),
);
/*@DOCKET_CACHE_EOF*/