<?php 
return array (
  'timestamp' => 1749764587,
  'site_id' => 1,
  'group' => 'transient',
  'key' => 'ecwid_products_42ead9b3ddbba2a20bf704a26aa2fbf6',
  'type' => 'array',
  'timeout' => 1750369387,
  'data' => 
  array (
    'time' => 1749764587,
    'data' => 
    (object) array(
       'id' => 758879709,
       'sku' => '0006',
       'thumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759307.jpg',
       'unlimited' => true,
       'inStock' => true,
       'name' => 'SAMPLE. Yellow Fluffy Sweater',
       'nameTranslated' => 
      (object) array(
         'en' => 'SAMPLE. Yellow Fluffy Sweater',
      ),
       'price' => 179.95,
       'priceInProductList' => 179.95,
       'defaultDisplayedPrice' => 179.95,
       'defaultDisplayedPriceFormatted' => '$179.95',
       'costPrice' => 0,
       'tax' => 
      (object) array(
         'taxable' => true,
         'defaultLocationIncludedTaxRate' => 0,
         'enabledManualTaxes' => 
        array (
        ),
         'taxClassCode' => 'default',
      ),
       'lowestPriceSettings' => 
      (object) array(
         'lowestPriceEnabled' => false,
      ),
       'isShippingRequired' => true,
       'hasFreeShipping' => true,
       'weight' => 0,
       'url' => 'https://dcandles.ctrlaltcarter.com/store/sample-yellow-fluffy-sweater',
       'autogeneratedSlug' => 'sample-yellow-fluffy-sweater',
       'customSlug' => '',
       'created' => '2025-06-12 00:16:12 +0000',
       'updated' => '2025-06-12 00:16:12 +0000',
       'createTimestamp' => 1749687372,
       'updateTimestamp' => 1749687372,
       'productClassId' => 0,
       'enabled' => true,
       'options' => 
      array (
      ),
       'warningLimit' => 0,
       'fixedShippingRateOnly' => false,
       'fixedShippingRate' => 0,
       'shipping' => 
      (object) array(
         'type' => 'GLOBAL_METHODS',
         'methodMarkup' => 0,
         'flatRate' => 0,
         'disabledMethods' => 
        array (
        ),
         'enabledMethods' => 
        array (
        ),
      ),
       'defaultCombinationId' => 0,
       'imageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759305.jpg',
       'smallThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759304.jpg',
       'hdThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759306.jpg',
       'originalImageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759303.jpg',
       'originalImage' => 
      (object) array(
         'url' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759303.jpg',
         'width' => 1280,
         'height' => 1920,
      ),
       'borderInfo' => 
      (object) array(
         'dominatingColor' => 
        (object) array(
           'red' => 233,
           'green' => 236,
           'blue' => 245,
           'alpha' => 255,
        ),
         'homogeneity' => true,
      ),
       'description' => '<p>Always wanted to feel like you are wearing a cloud? We have a right sweater for you.
				Soft, fluffy fabric guarantee mind-blowing comfort and makes it an indispensable item in your closet.
				The sweater has a regular fit, long puffy sleeves and a round neck. In addition, the item has a
				wonderful yellow color that makes you smile everytime you look at it.</p><div>Great to wear
				on its own or with a tank top underneath. Pair it with our bright yellow track pants or your favorite
				shorts.</div><div>This item comes in one size.<br></div><div><strong>Fabric
				& care<br></strong></div><p><strong>Material</strong>: 50%
				Polyamide, 30% Viscose, 20% Polyester<br><strong>Color</strong>: Yellow<br><strong>Fit</strong>:
				Relaxed<br>Machine wash. Use cold water to help prevent shrinking or pilling and a small amount of
				a detergent that’s free of unnecessary chemicals, dyes, phosphates, or parabens.<br>Do not
				bleach<br></p>
			',
       'descriptionTranslated' => 
      (object) array(
         'en' => '<p>Always wanted to feel like you are wearing a cloud? We have a right sweater for you.
				Soft, fluffy fabric guarantee mind-blowing comfort and makes it an indispensable item in your closet.
				The sweater has a regular fit, long puffy sleeves and a round neck. In addition, the item has a
				wonderful yellow color that makes you smile everytime you look at it.</p><div>Great to wear
				on its own or with a tank top underneath. Pair it with our bright yellow track pants or your favorite
				shorts.</div><div>This item comes in one size.<br></div><div><strong>Fabric
				& care<br></strong></div><p><strong>Material</strong>: 50%
				Polyamide, 30% Viscose, 20% Polyester<br><strong>Color</strong>: Yellow<br><strong>Fit</strong>:
				Relaxed<br>Machine wash. Use cold water to help prevent shrinking or pilling and a small amount of
				a detergent that’s free of unnecessary chemicals, dyes, phosphates, or parabens.<br>Do not
				bleach<br></p>
			',
      ),
       'galleryImages' => 
      array (
        0 => 
        (object) array(
           'id' => 1,
           'url' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751845.jpg',
           'thumbnail' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751846.jpg',
           'originalImageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751845.jpg',
           'imageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751847.jpg',
           'hdThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751848.jpg',
           'thumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751849.jpg',
           'smallThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751846.jpg',
           'width' => 1280,
           'height' => 1920,
           'orderBy' => 0,
           'borderInfo' => 
          (object) array(
             'dominatingColor' => 
            (object) array(
               'red' => 224,
               'green' => 223,
               'blue' => 229,
               'alpha' => 255,
            ),
             'homogeneity' => true,
          ),
        ),
        1 => 
        (object) array(
           'id' => 2,
           'url' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761042.jpg',
           'thumbnail' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761043.jpg',
           'originalImageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761042.jpg',
           'imageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761044.jpg',
           'hdThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761045.jpg',
           'thumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761046.jpg',
           'smallThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761043.jpg',
           'width' => 1280,
           'height' => 1920,
           'orderBy' => 1,
           'borderInfo' => 
          (object) array(
             'dominatingColor' => 
            (object) array(
               'red' => 230,
               'green' => 218,
               'blue' => 196,
               'alpha' => 255,
            ),
             'homogeneity' => false,
          ),
        ),
      ),
       'media' => 
      (object) array(
         'images' => 
        array (
          0 => 
          (object) array(
             'id' => '0',
             'isMain' => true,
             'orderBy' => 0,
             'image160pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759304.jpg',
             'image400pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759307.jpg',
             'image800pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759306.jpg',
             'image1500pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759305.jpg',
             'imageOriginalUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759303.jpg',
          ),
          1 => 
          (object) array(
             'id' => '1',
             'isMain' => false,
             'orderBy' => 1,
             'image160pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751846.jpg',
             'image400pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751849.jpg',
             'image800pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751848.jpg',
             'image1500pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751847.jpg',
             'imageOriginalUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751845.jpg',
          ),
          2 => 
          (object) array(
             'id' => '2',
             'isMain' => false,
             'orderBy' => 2,
             'image160pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761043.jpg',
             'image400pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761046.jpg',
             'image800pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761045.jpg',
             'image1500pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761044.jpg',
             'imageOriginalUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761042.jpg',
          ),
        ),
         'videos' => 
        array (
        ),
      ),
       'categoryIds' => 
      array (
      ),
       'categories' => 
      array (
      ),
       'defaultCategoryId' => 0,
       'attributes' => 
      array (
      ),
       'files' => 
      array (
      ),
       'relatedProducts' => 
      (object) array(
         'productIds' => 
        array (
        ),
         'relatedCategory' => 
        (object) array(
           'enabled' => false,
           'categoryId' => 0,
           'productCount' => 1,
        ),
      ),
       'combinations' => 
      array (
      ),
       'volume' => 0,
       'showOnFrontpage' => 8,
       'isSampleProduct' => true,
       'googleItemCondition' => 'NEW',
       'isGiftCard' => false,
       'discountsAllowed' => true,
       'productCondition' => 'NEW',
       'outOfStockVisibilityBehaviour' => 'SHOW',
       'seo_link' => 'https://dcandles.ctrlaltcarter.com/store/sample-yellow-fluffy-sweater',
    ),
  ),
);
/*@DOCKET_CACHE_EOF*/