<?php 
return array (
  'timestamp' => 1749764587,
  'site_id' => 1,
  'group' => 'transient',
  'key' => 'ecwid_products_f79de1f0cca714d21fca7561566b990b',
  'type' => 'array',
  'timeout' => 1750369387,
  'data' => 
  array (
    'time' => 1749764587,
    'data' => 
    (object) array(
       'id' => 758879711,
       'sku' => '0002',
       'thumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722398.jpg',
       'unlimited' => true,
       'inStock' => true,
       'name' => 'SAMPLE. Blue Sleeveless Coverall',
       'nameTranslated' => 
      (object) array(
         'en' => 'SAMPLE. Blue Sleeveless Coverall',
      ),
       'price' => 49.95,
       'priceInProductList' => 49.95,
       'defaultDisplayedPrice' => 49.95,
       'defaultDisplayedPriceFormatted' => '$49.95',
       'costPrice' => 0,
       'tax' => 
      (object) array(
         'taxable' => true,
         'defaultLocationIncludedTaxRate' => 0,
         'enabledManualTaxes' => 
        array (
        ),
         'taxClassCode' => 'default',
      ),
       'lowestPriceSettings' => 
      (object) array(
         'lowestPriceEnabled' => false,
      ),
       'isShippingRequired' => true,
       'hasFreeShipping' => true,
       'weight' => 0,
       'url' => 'https://dcandles.ctrlaltcarter.com/store/sample-blue-sleeveless-coverall',
       'autogeneratedSlug' => 'sample-blue-sleeveless-coverall',
       'customSlug' => '',
       'created' => '2025-06-12 00:16:12 +0000',
       'updated' => '2025-06-12 00:16:12 +0000',
       'createTimestamp' => 1749687372,
       'updateTimestamp' => 1749687372,
       'productClassId' => 0,
       'enabled' => true,
       'options' => 
      array (
        0 => 
        (object) array(
           'type' => 'SIZE',
           'name' => 'Size',
           'nameTranslated' => 
          (object) array(
             'en' => 'Size',
          ),
           'choices' => 
          array (
            0 => 
            (object) array(
               'text' => '32',
               'textTranslated' => 
              (object) array(
                 'en' => '32',
              ),
               'priceModifier' => 0,
               'priceModifierType' => 'ABSOLUTE',
            ),
            1 => 
            (object) array(
               'text' => '33',
               'textTranslated' => 
              (object) array(
                 'en' => '33',
              ),
               'priceModifier' => 0,
               'priceModifierType' => 'ABSOLUTE',
            ),
            2 => 
            (object) array(
               'text' => '34',
               'textTranslated' => 
              (object) array(
                 'en' => '34',
              ),
               'priceModifier' => 0,
               'priceModifierType' => 'ABSOLUTE',
            ),
            3 => 
            (object) array(
               'text' => '36',
               'textTranslated' => 
              (object) array(
                 'en' => '36',
              ),
               'priceModifier' => 0,
               'priceModifierType' => 'ABSOLUTE',
            ),
          ),
           'defaultChoice' => 0,
           'required' => false,
        ),
      ),
       'warningLimit' => 0,
       'fixedShippingRateOnly' => false,
       'fixedShippingRate' => 0,
       'shipping' => 
      (object) array(
         'type' => 'GLOBAL_METHODS',
         'methodMarkup' => 0,
         'flatRate' => 0,
         'disabledMethods' => 
        array (
        ),
         'enabledMethods' => 
        array (
        ),
      ),
       'defaultCombinationId' => 0,
       'imageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722396.jpg',
       'smallThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722395.jpg',
       'hdThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722397.jpg',
       'originalImageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722394.jpg',
       'originalImage' => 
      (object) array(
         'url' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722394.jpg',
         'width' => 1280,
         'height' => 1920,
      ),
       'borderInfo' => 
      (object) array(
         'dominatingColor' => 
        (object) array(
           'red' => 231,
           'green' => 230,
           'blue' => 226,
           'alpha' => 255,
        ),
         'homogeneity' => true,
      ),
       'description' => '<p>This boho style blue jeans coverall has strong summer vibes. Inspired by freedom and
				youth, this coverall was designed to bring you only good memories. Casual yet stylish, this sleeveless
				overall will leave you looking effortlessly cool. </p><p>Add bright socks, high platform
				shoes, and here you are, the coolest girl in town.</p><p><strong style="background-color:
				initial;">Fabric & care</strong></p><p><strong>Material</strong>:
				70% Cotton, 15% Polyester, 15% Spandex<br><strong>Color</strong>: Blue<br><strong>Fit</strong>:
				Relaxed<br><strong>Sleeve type</strong>: Sleeveless<br>Machine washable at max
				40°C with a non-bleach or phosphorus powder. </p>
			',
       'descriptionTranslated' => 
      (object) array(
         'en' => '<p>This boho style blue jeans coverall has strong summer vibes. Inspired by freedom and
				youth, this coverall was designed to bring you only good memories. Casual yet stylish, this sleeveless
				overall will leave you looking effortlessly cool. </p><p>Add bright socks, high platform
				shoes, and here you are, the coolest girl in town.</p><p><strong style="background-color:
				initial;">Fabric & care</strong></p><p><strong>Material</strong>:
				70% Cotton, 15% Polyester, 15% Spandex<br><strong>Color</strong>: Blue<br><strong>Fit</strong>:
				Relaxed<br><strong>Sleeve type</strong>: Sleeveless<br>Machine washable at max
				40°C with a non-bleach or phosphorus powder. </p>
			',
      ),
       'galleryImages' => 
      array (
        0 => 
        (object) array(
           'id' => 1,
           'url' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722399.jpg',
           'thumbnail' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722400.jpg',
           'originalImageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722399.jpg',
           'imageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722401.jpg',
           'hdThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722402.jpg',
           'thumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722403.jpg',
           'smallThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722400.jpg',
           'width' => 1280,
           'height' => 1920,
           'orderBy' => 0,
           'borderInfo' => 
          (object) array(
             'dominatingColor' => 
            (object) array(
               'red' => 192,
               'green' => 203,
               'blue' => 217,
               'alpha' => 255,
            ),
             'homogeneity' => false,
          ),
        ),
        1 => 
        (object) array(
           'id' => 2,
           'url' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761017.jpg',
           'thumbnail' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761018.jpg',
           'originalImageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761017.jpg',
           'imageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761019.jpg',
           'hdThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761020.jpg',
           'thumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761021.jpg',
           'smallThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761018.jpg',
           'width' => 1280,
           'height' => 1920,
           'orderBy' => 1,
           'borderInfo' => 
          (object) array(
             'dominatingColor' => 
            (object) array(
               'red' => 228,
               'green' => 228,
               'blue' => 230,
               'alpha' => 255,
            ),
             'homogeneity' => true,
          ),
        ),
      ),
       'media' => 
      (object) array(
         'images' => 
        array (
          0 => 
          (object) array(
             'id' => '0',
             'isMain' => true,
             'orderBy' => 0,
             'image160pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722395.jpg',
             'image400pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722398.jpg',
             'image800pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722397.jpg',
             'image1500pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722396.jpg',
             'imageOriginalUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722394.jpg',
          ),
          1 => 
          (object) array(
             'id' => '1',
             'isMain' => false,
             'orderBy' => 1,
             'image160pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722400.jpg',
             'image400pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722403.jpg',
             'image800pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722402.jpg',
             'image1500pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722401.jpg',
             'imageOriginalUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722399.jpg',
          ),
          2 => 
          (object) array(
             'id' => '2',
             'isMain' => false,
             'orderBy' => 2,
             'image160pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761018.jpg',
             'image400pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761021.jpg',
             'image800pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761020.jpg',
             'image1500pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761019.jpg',
             'imageOriginalUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761017.jpg',
          ),
        ),
         'videos' => 
        array (
        ),
      ),
       'categoryIds' => 
      array (
      ),
       'categories' => 
      array (
      ),
       'defaultCategoryId' => 0,
       'attributes' => 
      array (
      ),
       'files' => 
      array (
      ),
       'relatedProducts' => 
      (object) array(
         'productIds' => 
        array (
        ),
         'relatedCategory' => 
        (object) array(
           'enabled' => false,
           'categoryId' => 0,
           'productCount' => 1,
        ),
      ),
       'combinations' => 
      array (
      ),
       'volume' => 0,
       'showOnFrontpage' => 2,
       'isSampleProduct' => true,
       'googleItemCondition' => 'NEW',
       'isGiftCard' => false,
       'discountsAllowed' => true,
       'productCondition' => 'NEW',
       'outOfStockVisibilityBehaviour' => 'SHOW',
       'seo_link' => 'https://dcandles.ctrlaltcarter.com/store/sample-blue-sleeveless-coverall',
    ),
  ),
);
/*@DOCKET_CACHE_EOF*/