<?php 
return array (
  'timestamp' => 1749764587,
  'site_id' => 1,
  'group' => 'transient',
  'key' => 'ecwid_products_3e2a72cbaf33a417305ee9c5a4901054',
  'type' => 'array',
  'timeout' => 1750369387,
  'data' => 
  array (
    'time' => 1749764587,
    'data' => 
    (object) array(
       'id' => 758879707,
       'sku' => '0005',
       'thumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761031.jpg',
       'unlimited' => true,
       'inStock' => true,
       'name' => 'SAMPLE. Pink Hoodie',
       'nameTranslated' => 
      (object) array(
         'en' => 'SAMPLE. Pink Hoodie',
      ),
       'price' => 39.95,
       'priceInProductList' => 39.95,
       'defaultDisplayedPrice' => 39.95,
       'defaultDisplayedPriceFormatted' => '$39.95',
       'costPrice' => 0,
       'tax' => 
      (object) array(
         'taxable' => true,
         'defaultLocationIncludedTaxRate' => 0,
         'enabledManualTaxes' => 
        array (
        ),
         'taxClassCode' => 'default',
      ),
       'lowestPriceSettings' => 
      (object) array(
         'lowestPriceEnabled' => false,
      ),
       'isShippingRequired' => true,
       'hasFreeShipping' => true,
       'weight' => 0,
       'url' => 'https://dcandles.ctrlaltcarter.com/store/sample-pink-hoodie',
       'autogeneratedSlug' => 'sample-pink-hoodie',
       'customSlug' => '',
       'created' => '2025-06-12 00:16:12 +0000',
       'updated' => '2025-06-12 00:16:12 +0000',
       'createTimestamp' => 1749687372,
       'updateTimestamp' => 1749687372,
       'productClassId' => 0,
       'enabled' => true,
       'options' => 
      array (
        0 => 
        (object) array(
           'type' => 'SIZE',
           'name' => 'Size',
           'nameTranslated' => 
          (object) array(
             'en' => 'Size',
          ),
           'choices' => 
          array (
            0 => 
            (object) array(
               'text' => 'S',
               'textTranslated' => 
              (object) array(
                 'en' => 'S',
              ),
               'priceModifier' => 0,
               'priceModifierType' => 'ABSOLUTE',
            ),
            1 => 
            (object) array(
               'text' => 'M',
               'textTranslated' => 
              (object) array(
                 'en' => 'M',
              ),
               'priceModifier' => 0,
               'priceModifierType' => 'ABSOLUTE',
            ),
            2 => 
            (object) array(
               'text' => 'L',
               'textTranslated' => 
              (object) array(
                 'en' => 'L',
              ),
               'priceModifier' => 0,
               'priceModifierType' => 'ABSOLUTE',
            ),
          ),
           'defaultChoice' => 0,
           'required' => false,
        ),
      ),
       'warningLimit' => 0,
       'fixedShippingRateOnly' => false,
       'fixedShippingRate' => 0,
       'shipping' => 
      (object) array(
         'type' => 'GLOBAL_METHODS',
         'methodMarkup' => 0,
         'flatRate' => 0,
         'disabledMethods' => 
        array (
        ),
         'enabledMethods' => 
        array (
        ),
      ),
       'defaultCombinationId' => 0,
       'imageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761029.jpg',
       'smallThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761028.jpg',
       'hdThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761030.jpg',
       'originalImageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761027.jpg',
       'originalImage' => 
      (object) array(
         'url' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761027.jpg',
         'width' => 1280,
         'height' => 1920,
      ),
       'borderInfo' => 
      (object) array(
         'dominatingColor' => 
        (object) array(
           'red' => 228,
           'green' => 228,
           'blue' => 230,
           'alpha' => 255,
        ),
         'homogeneity' => true,
      ),
       'description' => '<div>Meet our 100% organic cotton hoodie inspired by the beautiful shade of Japanese
				cherry blossom. This soft and comfortable hoodie with a loop back texture inside and a finishing that
				provides extra softness became bestseller in no time. Pair with your favorite skirt or shorts and get
				ready to shine like a diamond. </div><div>Sleeve length starts with 16 inches (S-size), and
				goes up to 18 inches (L-size).</div><div></div><p>Available in S, M and L sizes.
				</p><div></div><p><strong>Fabric & care</strong></p><p><strong>Material</strong>:
				100% Organic Cotton<br><strong>Color</strong>: Pink<br><strong>Fit</strong>:
				Relaxed<br>Machine wash at max 40°C gentle<br>Do not bleach<br>Can be dry cleaned<br>Do
				not wash with white clothes</p>
			',
       'descriptionTranslated' => 
      (object) array(
         'en' => '<div>Meet our 100% organic cotton hoodie inspired by the beautiful shade of Japanese
				cherry blossom. This soft and comfortable hoodie with a loop back texture inside and a finishing that
				provides extra softness became bestseller in no time. Pair with your favorite skirt or shorts and get
				ready to shine like a diamond. </div><div>Sleeve length starts with 16 inches (S-size), and
				goes up to 18 inches (L-size).</div><div></div><p>Available in S, M and L sizes.
				</p><div></div><p><strong>Fabric & care</strong></p><p><strong>Material</strong>:
				100% Organic Cotton<br><strong>Color</strong>: Pink<br><strong>Fit</strong>:
				Relaxed<br>Machine wash at max 40°C gentle<br>Do not bleach<br>Can be dry cleaned<br>Do
				not wash with white clothes</p>
			',
      ),
       'galleryImages' => 
      array (
        0 => 
        (object) array(
           'id' => 1,
           'url' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051758332.jpg',
           'thumbnail' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051758333.jpg',
           'originalImageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051758332.jpg',
           'imageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051758334.jpg',
           'hdThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051758335.jpg',
           'thumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051758336.jpg',
           'smallThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051758333.jpg',
           'width' => 1280,
           'height' => 1920,
           'orderBy' => 0,
           'borderInfo' => 
          (object) array(
             'dominatingColor' => 
            (object) array(
               'red' => 236,
               'green' => 209,
               'blue' => 224,
               'alpha' => 255,
            ),
             'homogeneity' => false,
          ),
        ),
        1 => 
        (object) array(
           'id' => 2,
           'url' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722409.jpg',
           'thumbnail' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722410.jpg',
           'originalImageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722409.jpg',
           'imageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722411.jpg',
           'hdThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722412.jpg',
           'thumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722413.jpg',
           'smallThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722410.jpg',
           'width' => 1280,
           'height' => 1920,
           'orderBy' => 1,
           'borderInfo' => 
          (object) array(
             'dominatingColor' => 
            (object) array(
               'red' => 225,
               'green' => 222,
               'blue' => 227,
               'alpha' => 255,
            ),
             'homogeneity' => false,
          ),
        ),
      ),
       'media' => 
      (object) array(
         'images' => 
        array (
          0 => 
          (object) array(
             'id' => '0',
             'isMain' => true,
             'orderBy' => 0,
             'image160pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761028.jpg',
             'image400pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761031.jpg',
             'image800pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761030.jpg',
             'image1500pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761029.jpg',
             'imageOriginalUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761027.jpg',
          ),
          1 => 
          (object) array(
             'id' => '1',
             'isMain' => false,
             'orderBy' => 1,
             'image160pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051758333.jpg',
             'image400pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051758336.jpg',
             'image800pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051758335.jpg',
             'image1500pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051758334.jpg',
             'imageOriginalUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051758332.jpg',
          ),
          2 => 
          (object) array(
             'id' => '2',
             'isMain' => false,
             'orderBy' => 2,
             'image160pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722410.jpg',
             'image400pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722413.jpg',
             'image800pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722412.jpg',
             'image1500pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722411.jpg',
             'imageOriginalUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051722409.jpg',
          ),
        ),
         'videos' => 
        array (
        ),
      ),
       'categoryIds' => 
      array (
      ),
       'categories' => 
      array (
      ),
       'defaultCategoryId' => 0,
       'attributes' => 
      array (
      ),
       'files' => 
      array (
      ),
       'relatedProducts' => 
      (object) array(
         'productIds' => 
        array (
        ),
         'relatedCategory' => 
        (object) array(
           'enabled' => false,
           'categoryId' => 0,
           'productCount' => 1,
        ),
      ),
       'combinations' => 
      array (
      ),
       'volume' => 0,
       'showOnFrontpage' => 9,
       'isSampleProduct' => true,
       'googleItemCondition' => 'NEW',
       'isGiftCard' => false,
       'discountsAllowed' => true,
       'productCondition' => 'NEW',
       'outOfStockVisibilityBehaviour' => 'SHOW',
       'seo_link' => 'https://dcandles.ctrlaltcarter.com/store/sample-pink-hoodie',
    ),
  ),
);
/*@DOCKET_CACHE_EOF*/