<?php 
return array (
  'timestamp' => 1749764587,
  'site_id' => 1,
  'group' => 'transient',
  'key' => 'ecwid_products_04ee63e4f08f53d18de19effe1445f56',
  'type' => 'array',
  'timeout' => 1750369387,
  'data' => 
  array (
    'time' => 1749764587,
    'data' => 
    (object) array(
       'id' => 758879710,
       'sku' => '0001',
       'thumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751822.jpg',
       'unlimited' => true,
       'inStock' => true,
       'name' => 'SAMPLE. Blue Denim Long Skirt',
       'nameTranslated' => 
      (object) array(
         'en' => 'SAMPLE. Blue Denim Long Skirt',
      ),
       'price' => 19.95,
       'priceInProductList' => 19.95,
       'defaultDisplayedPrice' => 19.95,
       'defaultDisplayedPriceFormatted' => '$19.95',
       'costPrice' => 0,
       'tax' => 
      (object) array(
         'taxable' => true,
         'defaultLocationIncludedTaxRate' => 0,
         'enabledManualTaxes' => 
        array (
        ),
         'taxClassCode' => 'default',
      ),
       'lowestPriceSettings' => 
      (object) array(
         'lowestPriceEnabled' => false,
      ),
       'isShippingRequired' => true,
       'hasFreeShipping' => true,
       'weight' => 0,
       'url' => 'https://dcandles.ctrlaltcarter.com/store/sample-blue-denim-long-skirt',
       'autogeneratedSlug' => 'sample-blue-denim-long-skirt',
       'customSlug' => '',
       'created' => '2025-06-12 00:16:12 +0000',
       'updated' => '2025-06-12 00:16:12 +0000',
       'createTimestamp' => 1749687372,
       'updateTimestamp' => 1749687372,
       'productClassId' => 0,
       'enabled' => true,
       'options' => 
      array (
        0 => 
        (object) array(
           'type' => 'SIZE',
           'name' => 'Size',
           'nameTranslated' => 
          (object) array(
             'en' => 'Size',
          ),
           'choices' => 
          array (
            0 => 
            (object) array(
               'text' => 'S',
               'textTranslated' => 
              (object) array(
                 'en' => 'S',
              ),
               'priceModifier' => 0,
               'priceModifierType' => 'ABSOLUTE',
            ),
            1 => 
            (object) array(
               'text' => 'M',
               'textTranslated' => 
              (object) array(
                 'en' => 'M',
              ),
               'priceModifier' => 0,
               'priceModifierType' => 'ABSOLUTE',
            ),
            2 => 
            (object) array(
               'text' => 'L',
               'textTranslated' => 
              (object) array(
                 'en' => 'L',
              ),
               'priceModifier' => 0,
               'priceModifierType' => 'ABSOLUTE',
            ),
          ),
           'defaultChoice' => 0,
           'required' => false,
        ),
      ),
       'warningLimit' => 0,
       'fixedShippingRateOnly' => false,
       'fixedShippingRate' => 0,
       'shipping' => 
      (object) array(
         'type' => 'GLOBAL_METHODS',
         'methodMarkup' => 0,
         'flatRate' => 0,
         'disabledMethods' => 
        array (
        ),
         'enabledMethods' => 
        array (
        ),
      ),
       'defaultCombinationId' => 0,
       'imageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751820.jpg',
       'smallThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751819.jpg',
       'hdThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751821.jpg',
       'originalImageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751818.jpg',
       'originalImage' => 
      (object) array(
         'url' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751818.jpg',
         'width' => 1280,
         'height' => 1919,
      ),
       'borderInfo' => 
      (object) array(
         'dominatingColor' => 
        (object) array(
           'red' => 236,
           'green' => 237,
           'blue' => 241,
           'alpha' => 255,
        ),
         'homogeneity' => true,
      ),
       'description' => '<p>This playfull skirt is a perfect piece to guarantee you true urban look. Pair it with
				a white top, shirt with print, or even a small dress, and you are all set. </p><p>Made from
				a stretch woven denim, this A-line skirt has a cutout at front and a cute fringe-like hem.</p><div>Available
				in S, M, and L sizes.</div><p><strong>Fabric & care</strong><br></p><p><strong>Material</strong>:
				85% Cotton and 15% Spandex<br><strong>Color</strong>: Blue<br><strong>Fit</strong>:
				Relaxed<br>Wash in cool or cold water with similar colors, with a minimal amount of detergent.</p>
			',
       'descriptionTranslated' => 
      (object) array(
         'en' => '<p>This playfull skirt is a perfect piece to guarantee you true urban look. Pair it with
				a white top, shirt with print, or even a small dress, and you are all set. </p><p>Made from
				a stretch woven denim, this A-line skirt has a cutout at front and a cute fringe-like hem.</p><div>Available
				in S, M, and L sizes.</div><p><strong>Fabric & care</strong><br></p><p><strong>Material</strong>:
				85% Cotton and 15% Spandex<br><strong>Color</strong>: Blue<br><strong>Fit</strong>:
				Relaxed<br>Wash in cool or cold water with similar colors, with a minimal amount of detergent.</p>
			',
      ),
       'galleryImages' => 
      array (
        0 => 
        (object) array(
           'id' => 1,
           'url' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051763257.jpg',
           'thumbnail' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051763258.jpg',
           'originalImageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051763257.jpg',
           'imageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051763259.jpg',
           'hdThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051763260.jpg',
           'thumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051763261.jpg',
           'smallThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051763258.jpg',
           'width' => 1280,
           'height' => 1920,
           'orderBy' => 0,
           'borderInfo' => 
          (object) array(
             'dominatingColor' => 
            (object) array(
               'red' => 233,
               'green' => 232,
               'blue' => 230,
               'alpha' => 255,
            ),
             'homogeneity' => true,
          ),
        ),
        1 => 
        (object) array(
           'id' => 2,
           'url' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051763262.jpg',
           'thumbnail' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051763263.jpg',
           'originalImageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051763262.jpg',
           'imageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051763264.jpg',
           'hdThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051763265.jpg',
           'thumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051763266.jpg',
           'smallThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051763263.jpg',
           'width' => 1280,
           'height' => 1920,
           'orderBy' => 1,
           'borderInfo' => 
          (object) array(
             'dominatingColor' => 
            (object) array(
               'red' => 233,
               'green' => 233,
               'blue' => 232,
               'alpha' => 255,
            ),
             'homogeneity' => false,
          ),
        ),
      ),
       'media' => 
      (object) array(
         'images' => 
        array (
          0 => 
          (object) array(
             'id' => '0',
             'isMain' => true,
             'orderBy' => 0,
             'image160pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751819.jpg',
             'image400pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751822.jpg',
             'image800pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751821.jpg',
             'image1500pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751820.jpg',
             'imageOriginalUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751818.jpg',
          ),
          1 => 
          (object) array(
             'id' => '1',
             'isMain' => false,
             'orderBy' => 1,
             'image160pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051763258.jpg',
             'image400pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051763261.jpg',
             'image800pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051763260.jpg',
             'image1500pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051763259.jpg',
             'imageOriginalUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051763257.jpg',
          ),
          2 => 
          (object) array(
             'id' => '2',
             'isMain' => false,
             'orderBy' => 2,
             'image160pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051763263.jpg',
             'image400pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051763266.jpg',
             'image800pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051763265.jpg',
             'image1500pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051763264.jpg',
             'imageOriginalUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051763262.jpg',
          ),
        ),
         'videos' => 
        array (
        ),
      ),
       'categoryIds' => 
      array (
      ),
       'categories' => 
      array (
      ),
       'defaultCategoryId' => 0,
       'attributes' => 
      array (
      ),
       'files' => 
      array (
      ),
       'relatedProducts' => 
      (object) array(
         'productIds' => 
        array (
        ),
         'relatedCategory' => 
        (object) array(
           'enabled' => false,
           'categoryId' => 0,
           'productCount' => 1,
        ),
      ),
       'combinations' => 
      array (
      ),
       'volume' => 0,
       'showOnFrontpage' => 6,
       'isSampleProduct' => true,
       'googleItemCondition' => 'NEW',
       'isGiftCard' => false,
       'discountsAllowed' => true,
       'productCondition' => 'NEW',
       'outOfStockVisibilityBehaviour' => 'SHOW',
       'seo_link' => 'https://dcandles.ctrlaltcarter.com/store/sample-blue-denim-long-skirt',
    ),
  ),
);
/*@DOCKET_CACHE_EOF*/