<?php 
return array (
  'timestamp' => 1749764587,
  'site_id' => 1,
  'group' => 'transient',
  'key' => 'ecwid_products_4ee504ec087ca57405a04addcb503d53',
  'type' => 'array',
  'timeout' => 1750369387,
  'data' => 
  array (
    'time' => 1749764587,
    'data' => 
    (object) array(
       'id' => 758879706,
       'sku' => '0003',
       'thumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751832.jpg',
       'unlimited' => true,
       'inStock' => true,
       'name' => 'SAMPLE. Bright Yellow Track Pants',
       'nameTranslated' => 
      (object) array(
         'en' => 'SAMPLE. Bright Yellow Track Pants',
      ),
       'price' => 19.95,
       'priceInProductList' => 19.95,
       'defaultDisplayedPrice' => 19.95,
       'defaultDisplayedPriceFormatted' => '$19.95',
       'costPrice' => 0,
       'tax' => 
      (object) array(
         'taxable' => true,
         'defaultLocationIncludedTaxRate' => 0,
         'enabledManualTaxes' => 
        array (
        ),
         'taxClassCode' => 'default',
      ),
       'lowestPriceSettings' => 
      (object) array(
         'lowestPriceEnabled' => false,
      ),
       'isShippingRequired' => true,
       'hasFreeShipping' => true,
       'weight' => 0,
       'url' => 'https://dcandles.ctrlaltcarter.com/store/sample-bright-yellow-track-pants',
       'autogeneratedSlug' => 'sample-bright-yellow-track-pants',
       'customSlug' => '',
       'created' => '2025-06-12 00:16:12 +0000',
       'updated' => '2025-06-12 00:16:12 +0000',
       'createTimestamp' => 1749687372,
       'updateTimestamp' => 1749687372,
       'productClassId' => 0,
       'enabled' => true,
       'options' => 
      array (
        0 => 
        (object) array(
           'type' => 'SIZE',
           'name' => 'Size',
           'nameTranslated' => 
          (object) array(
             'en' => 'Size',
          ),
           'choices' => 
          array (
            0 => 
            (object) array(
               'text' => 'S',
               'textTranslated' => 
              (object) array(
                 'en' => 'S',
              ),
               'priceModifier' => 0,
               'priceModifierType' => 'ABSOLUTE',
            ),
            1 => 
            (object) array(
               'text' => 'M',
               'textTranslated' => 
              (object) array(
                 'en' => 'M',
              ),
               'priceModifier' => 0,
               'priceModifierType' => 'ABSOLUTE',
            ),
            2 => 
            (object) array(
               'text' => 'L',
               'textTranslated' => 
              (object) array(
                 'en' => 'L',
              ),
               'priceModifier' => 0,
               'priceModifierType' => 'ABSOLUTE',
            ),
          ),
           'defaultChoice' => 0,
           'required' => false,
        ),
      ),
       'warningLimit' => 0,
       'fixedShippingRateOnly' => false,
       'fixedShippingRate' => 0,
       'shipping' => 
      (object) array(
         'type' => 'GLOBAL_METHODS',
         'methodMarkup' => 0,
         'flatRate' => 0,
         'disabledMethods' => 
        array (
        ),
         'enabledMethods' => 
        array (
        ),
      ),
       'defaultCombinationId' => 0,
       'imageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751830.jpg',
       'smallThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751829.jpg',
       'hdThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751831.jpg',
       'originalImageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751828.jpg',
       'originalImage' => 
      (object) array(
         'url' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751828.jpg',
         'width' => 1280,
         'height' => 1920,
      ),
       'borderInfo' => 
      (object) array(
         'dominatingColor' => 
        (object) array(
           'red' => 225,
           'green' => 224,
           'blue' => 220,
           'alpha' => 255,
        ),
         'homogeneity' => true,
      ),
       'description' => '<p>Rump stunts are much cooler if you wear bright track pants while riding. These 100%
				cotton pants with deep front pockets are extremely comfortable to do tricks on skateboard. Warm enough
				for an early spring, they also will keep you cool in the hot weather. Wear them to skate, walk, or play
				switch on a couch. These pants will win you over once you try them on. </p><p><span></span></p><p>Perfectly
				paired with our red and white horizontal striped T-shirt or pink hoodie. </p><div>Available
				in S, M, and L sizes.</div><p><strong>Fabric & care</strong><br></p><p><strong>Material</strong>:
				100% Cotton<br><strong>Color</strong>: Yellow with a white stripe. <br><strong>Fit</strong>:
				Relaxed<br>Machine wash at max 40°C<br>Do not bleach<br>Do not wash with white
				clothes</p>
			',
       'descriptionTranslated' => 
      (object) array(
         'en' => '<p>Rump stunts are much cooler if you wear bright track pants while riding. These 100%
				cotton pants with deep front pockets are extremely comfortable to do tricks on skateboard. Warm enough
				for an early spring, they also will keep you cool in the hot weather. Wear them to skate, walk, or play
				switch on a couch. These pants will win you over once you try them on. </p><p><span></span></p><p>Perfectly
				paired with our red and white horizontal striped T-shirt or pink hoodie. </p><div>Available
				in S, M, and L sizes.</div><p><strong>Fabric & care</strong><br></p><p><strong>Material</strong>:
				100% Cotton<br><strong>Color</strong>: Yellow with a white stripe. <br><strong>Fit</strong>:
				Relaxed<br>Machine wash at max 40°C<br>Do not bleach<br>Do not wash with white
				clothes</p>
			',
      ),
       'galleryImages' => 
      array (
        0 => 
        (object) array(
           'id' => 1,
           'url' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051691214.jpg',
           'thumbnail' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051691215.jpg',
           'originalImageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051691214.jpg',
           'imageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051691216.jpg',
           'hdThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051691217.jpg',
           'thumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051691218.jpg',
           'smallThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051691215.jpg',
           'width' => 1280,
           'height' => 1920,
           'orderBy' => 0,
           'borderInfo' => 
          (object) array(
             'dominatingColor' => 
            (object) array(
               'red' => 230,
               'green' => 230,
               'blue' => 232,
               'alpha' => 255,
            ),
             'homogeneity' => true,
          ),
        ),
        1 => 
        (object) array(
           'id' => 2,
           'url' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761022.jpg',
           'thumbnail' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761023.jpg',
           'originalImageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761022.jpg',
           'imageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761024.jpg',
           'hdThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761025.jpg',
           'thumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761026.jpg',
           'smallThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761023.jpg',
           'width' => 1280,
           'height' => 1920,
           'orderBy' => 1,
           'borderInfo' => 
          (object) array(
             'dominatingColor' => 
            (object) array(
               'red' => 227,
               'green' => 227,
               'blue' => 227,
               'alpha' => 255,
            ),
             'homogeneity' => true,
          ),
        ),
      ),
       'media' => 
      (object) array(
         'images' => 
        array (
          0 => 
          (object) array(
             'id' => '0',
             'isMain' => true,
             'orderBy' => 0,
             'image160pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751829.jpg',
             'image400pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751832.jpg',
             'image800pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751831.jpg',
             'image1500pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751830.jpg',
             'imageOriginalUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051751828.jpg',
          ),
          1 => 
          (object) array(
             'id' => '1',
             'isMain' => false,
             'orderBy' => 1,
             'image160pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051691215.jpg',
             'image400pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051691218.jpg',
             'image800pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051691217.jpg',
             'image1500pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051691216.jpg',
             'imageOriginalUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051691214.jpg',
          ),
          2 => 
          (object) array(
             'id' => '2',
             'isMain' => false,
             'orderBy' => 2,
             'image160pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761023.jpg',
             'image400pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761026.jpg',
             'image800pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761025.jpg',
             'image1500pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761024.jpg',
             'imageOriginalUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051761022.jpg',
          ),
        ),
         'videos' => 
        array (
        ),
      ),
       'categoryIds' => 
      array (
      ),
       'categories' => 
      array (
      ),
       'defaultCategoryId' => 0,
       'attributes' => 
      array (
      ),
       'files' => 
      array (
      ),
       'relatedProducts' => 
      (object) array(
         'productIds' => 
        array (
        ),
         'relatedCategory' => 
        (object) array(
           'enabled' => false,
           'categoryId' => 0,
           'productCount' => 1,
        ),
      ),
       'combinations' => 
      array (
      ),
       'volume' => 0,
       'showOnFrontpage' => 4,
       'isSampleProduct' => true,
       'googleItemCondition' => 'NEW',
       'isGiftCard' => false,
       'discountsAllowed' => true,
       'productCondition' => 'NEW',
       'outOfStockVisibilityBehaviour' => 'SHOW',
       'seo_link' => 'https://dcandles.ctrlaltcarter.com/store/sample-bright-yellow-track-pants',
    ),
  ),
);
/*@DOCKET_CACHE_EOF*/