<?php 
return array (
  'timestamp' => 1749764587,
  'site_id' => 1,
  'group' => 'transient',
  'key' => 'ecwid_products_489e7ce6789e1920dbcb948ffd2ed5b6',
  'type' => 'array',
  'timeout' => 1750369387,
  'data' => 
  array (
    'time' => 1749764587,
    'data' => 
    (object) array(
       'id' => 758879705,
       'sku' => '0007',
       'thumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759302.jpg',
       'unlimited' => true,
       'inStock' => true,
       'name' => 'SAMPLE. Red and White Horizontal Striped T-Shirt',
       'nameTranslated' => 
      (object) array(
         'en' => 'SAMPLE. Red and White Horizontal Striped T-Shirt',
      ),
       'price' => 49.95,
       'priceInProductList' => 49.95,
       'defaultDisplayedPrice' => 49.95,
       'defaultDisplayedPriceFormatted' => '$49.95',
       'costPrice' => 0,
       'tax' => 
      (object) array(
         'taxable' => true,
         'defaultLocationIncludedTaxRate' => 0,
         'enabledManualTaxes' => 
        array (
        ),
         'taxClassCode' => 'default',
      ),
       'lowestPriceSettings' => 
      (object) array(
         'lowestPriceEnabled' => false,
      ),
       'isShippingRequired' => true,
       'hasFreeShipping' => true,
       'weight' => 0,
       'url' => 'https://dcandles.ctrlaltcarter.com/store/sample-red-and-white-horizontal-striped-t-shirt',
       'autogeneratedSlug' => 'sample-red-and-white-horizontal-striped-t-shirt',
       'customSlug' => '',
       'created' => '2025-06-12 00:16:12 +0000',
       'updated' => '2025-06-12 00:16:12 +0000',
       'createTimestamp' => 1749687372,
       'updateTimestamp' => 1749687372,
       'productClassId' => 0,
       'enabled' => true,
       'options' => 
      array (
        0 => 
        (object) array(
           'type' => 'SIZE',
           'name' => 'Size',
           'nameTranslated' => 
          (object) array(
             'en' => 'Size',
          ),
           'choices' => 
          array (
            0 => 
            (object) array(
               'text' => 'S',
               'textTranslated' => 
              (object) array(
                 'en' => 'S',
              ),
               'priceModifier' => 0,
               'priceModifierType' => 'ABSOLUTE',
            ),
            1 => 
            (object) array(
               'text' => 'M',
               'textTranslated' => 
              (object) array(
                 'en' => 'M',
              ),
               'priceModifier' => 0,
               'priceModifierType' => 'ABSOLUTE',
            ),
          ),
           'defaultChoice' => 0,
           'required' => false,
        ),
      ),
       'warningLimit' => 0,
       'fixedShippingRateOnly' => false,
       'fixedShippingRate' => 0,
       'shipping' => 
      (object) array(
         'type' => 'GLOBAL_METHODS',
         'methodMarkup' => 0,
         'flatRate' => 0,
         'disabledMethods' => 
        array (
        ),
         'enabledMethods' => 
        array (
        ),
      ),
       'defaultCombinationId' => 0,
       'imageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759300.jpg',
       'smallThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759299.jpg',
       'hdThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759301.jpg',
       'originalImageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759298.jpg',
       'originalImage' => 
      (object) array(
         'url' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759298.jpg',
         'width' => 1001,
         'height' => 1500,
      ),
       'borderInfo' => 
      (object) array(
         'dominatingColor' => 
        (object) array(
           'red' => 228,
           'green' => 224,
           'blue' => 221,
           'alpha' => 255,
        ),
         'homogeneity' => true,
      ),
       'description' => '<div>You can never have too many tees, right? Try something new with this red and white
				horizontal striped T-shirt made from 100%
				cotton and comfortable enough for the whole day. Great to wear under a hoody or on its own with your
				favorite denim for laid back everyday style. Simple yet stylish this is an essential piece for every
				closet.</div><div>The size chart dimension can be given as S and M.</div><div><strong>Fabric
				& care</strong><br></div><p><strong>Material</strong>: 100%
				Cotton<br><strong>Color</strong>: Pink<br><strong>Fit</strong>:
				Relaxed<br>Machine wash at max 40°C<br>Do not bleach<br>Do not wash with white
				clothes</p>
			',
       'descriptionTranslated' => 
      (object) array(
         'en' => '<div>You can never have too many tees, right? Try something new with this red and white
				horizontal striped T-shirt made from 100%
				cotton and comfortable enough for the whole day. Great to wear under a hoody or on its own with your
				favorite denim for laid back everyday style. Simple yet stylish this is an essential piece for every
				closet.</div><div>The size chart dimension can be given as S and M.</div><div><strong>Fabric
				& care</strong><br></div><p><strong>Material</strong>: 100%
				Cotton<br><strong>Color</strong>: Pink<br><strong>Fit</strong>:
				Relaxed<br>Machine wash at max 40°C<br>Do not bleach<br>Do not wash with white
				clothes</p>
			',
      ),
       'galleryImages' => 
      array (
        0 => 
        (object) array(
           'id' => 1,
           'url' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759762.jpg',
           'thumbnail' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759763.jpg',
           'originalImageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759762.jpg',
           'imageUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759764.jpg',
           'hdThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759765.jpg',
           'thumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759766.jpg',
           'smallThumbnailUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759763.jpg',
           'width' => 1280,
           'height' => 1920,
           'orderBy' => 0,
           'borderInfo' => 
          (object) array(
             'dominatingColor' => 
            (object) array(
               'red' => 227,
               'green' => 178,
               'blue' => 191,
               'alpha' => 255,
            ),
             'homogeneity' => false,
          ),
        ),
      ),
       'media' => 
      (object) array(
         'images' => 
        array (
          0 => 
          (object) array(
             'id' => '0',
             'isMain' => true,
             'orderBy' => 0,
             'image160pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759299.jpg',
             'image400pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759302.jpg',
             'image800pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759301.jpg',
             'image1500pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759300.jpg',
             'imageOriginalUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759298.jpg',
          ),
          1 => 
          (object) array(
             'id' => '1',
             'isMain' => false,
             'orderBy' => 1,
             'image160pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759763.jpg',
             'image400pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759766.jpg',
             'image800pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759765.jpg',
             'image1500pxUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759764.jpg',
             'imageOriginalUrl' => 'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759762.jpg',
          ),
        ),
         'videos' => 
        array (
        ),
      ),
       'categoryIds' => 
      array (
      ),
       'categories' => 
      array (
      ),
       'defaultCategoryId' => 0,
       'attributes' => 
      array (
      ),
       'files' => 
      array (
      ),
       'relatedProducts' => 
      (object) array(
         'productIds' => 
        array (
        ),
         'relatedCategory' => 
        (object) array(
           'enabled' => false,
           'categoryId' => 0,
           'productCount' => 1,
        ),
      ),
       'combinations' => 
      array (
      ),
       'volume' => 0,
       'showOnFrontpage' => 5,
       'isSampleProduct' => true,
       'googleItemCondition' => 'NEW',
       'isGiftCard' => false,
       'discountsAllowed' => true,
       'productCondition' => 'NEW',
       'outOfStockVisibilityBehaviour' => 'SHOW',
       'seo_link' => 'https://dcandles.ctrlaltcarter.com/store/sample-red-and-white-horizontal-striped-t-shirt',
    ),
  ),
);
/*@DOCKET_CACHE_EOF*/